# Generated by Django 4.2.2 on 2023-07-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('price', models.CharField(max_length=20, verbose_name='Price')),
                ('img_url', models.TextField(verbose_name='img_url')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shop',
            },
        ),
    ]
