# Generated by Django 4.2.2 on 2023-07-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aerticles',
            new_name='Articles',
        ),
    ]
