# Generated by Django 4.2.2 on 2023-07-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_aerticles_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='type_model',
            field=models.CharField(default=1, max_length=20, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
